---
title: "Advice for Constructing a First-Generation College Status Indicator (FGC):"
author: "ML"
format: html
editor: visual
output-file: "index.html"
---

The First-Generation College (FGC) Indicator is constructed using both parents' education information (i.e., variables `parent1` and `parent2`). Therefore, we'd suggest:

-   

    1)  **Ensure within-student coding consistency of `parent1` and `parent2`**. In this sample of college students, parental education is assumed to remain constant over time. However, two cases were identified where one parent's education level varied in a single semester but was consistent in preceding and following semesters. This discrepancy is treated as a coding error, corrected by replacing the irregular value with the mode of the consistent values. We created a Stata program to help you automate checking for such coding errors that could be used for all other time-constant variables (see Stata dofile).

-   

    2)  **Define parent education threshold**. In this analysis, FGC status is defined as neither parent having completed a college degree, even if one or both took some college courses (without earning a degree). Alternatively, FGC status could be defined more strictly as neither parent having taken any college level courses at all (see suggestion for Sensitivity Analysis below). This stricter definition would likely reduce the number of FGC students in the sample.

-   https://github.com/r4miao/FH_excercise.git

    3)  **Check for Missing Data of `parent1` and `parent2`**. If both parents' data are missing, FGC status is set to missing. If data for only one parent is missing, FGC is defined as 'No' if the available parent has completed college. If the available parent has not completed college, FGC status remains missing. For sensitivity analysis, we suggest defining FGC status based on any available parent education data, regardless of whether the available parent completed college. In this analysis, we did not perform a sensitivity analysis because only one individual had a parent with missing education data, and the available parent held a post-graduate degree, making FGC classification straightforward.

-   

    4)  **Sensitivity Analysis**. Conduct sensitivity analyses by (1) applying an alternative parental education threshold and (2) exploring different methods for handling missing parental data (especially as the amount of missing data may increase with larger datasets).

Access [Stata Coding](FGC_stata_coding.html) for the FGC variable.
